// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP-7sD03ei0kI8yCvxLM5wTbdAI5hLnsw',
    appId: '1:751072443811:web:ca77440bf2d5bb2da46e16',
    messagingSenderId: '751072443811',
    projectId: 'attendx-7d778',
    authDomain: 'attendx-7d778.firebaseapp.com',
    storageBucket: 'attendx-7d778.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLiiATyvWROrKUVz9Rdr4rMmDTkzSqtI8',
    appId: '1:751072443811:android:b282876d8704a9c7a46e16',
    messagingSenderId: '751072443811',
    projectId: 'attendx-7d778',
    storageBucket: 'attendx-7d778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPk-lwR5jean0Ft_GQGpyHL3PqpH-GAgE',
    appId: '1:751072443811:ios:04c300dd002a322ba46e16',
    messagingSenderId: '751072443811',
    projectId: 'attendx-7d778',
    storageBucket: 'attendx-7d778.firebasestorage.app',
    iosBundleId: 'com.attendx.attendx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPk-lwR5jean0Ft_GQGpyHL3PqpH-GAgE',
    appId: '1:751072443811:ios:04c300dd002a322ba46e16',
    messagingSenderId: '751072443811',
    projectId: 'attendx-7d778',
    storageBucket: 'attendx-7d778.firebasestorage.app',
    iosBundleId: 'com.attendx.attendx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP-7sD03ei0kI8yCvxLM5wTbdAI5hLnsw',
    appId: '1:751072443811:web:0db33760720cee6ba46e16',
    messagingSenderId: '751072443811',
    projectId: 'attendx-7d778',
    authDomain: 'attendx-7d778.firebaseapp.com',
    storageBucket: 'attendx-7d778.firebasestorage.app',
  );
}
